deployment:
  desiredReplicas: 2
  imageURL: IMAGE_URL
  imageVersion: IMAGE_VERSION
service:
  port: 8080
  targetPort: 8080
hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 15
configMap:
  DB_HOST: mysql-dev.mahdo.site